version: "3.9"

services:
  dev-ui:
    build: 
      context: .
      dockerfile: Dockerfile.dev
    volumes:
      - ./src:/usr/src/app/src
      - dist:/usr/src/app/dist
    environment: 
      - SERVER_BASE
    # Pack ui files with parcel watcher
    command: [ "dev-ui" ]
      
  dev:
    build: 
      context: .
      dockerfile: Dockerfile.dev
    volumes:
      - ./src:/usr/src/app/src
      - dist:/usr/src/app/dist
    environment: 
      - SERVER_BASE

volumes:
  dist:
